name: Deploy to Heroku

on:
  release:
    types: [released]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_APP: ${{ secrets.FLY_APP_NAME }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#      - name: Build with Gradle
#        run: |
#          chmod +x gradlew
#          ./gradlew stage
  deploy:
    runs-on: ubuntu-latest
    environment: discord production
    needs: [ build ]
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
