name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g: 1.2.3)'
        required: true
        type: string
      snapshot_version:
        description: 'Snapshot version (e.g: 1.3.0-SNAPSHOT)'
        required: true
        type: string

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.RELEASE_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.RELEASE_GPG_PASSPHRASE }}
          git_user_signingkey: true
      - name: Run Gradle release
        run: |
          gradle release -Prelease.releaseVersion=${{ inputs.version }} -Prelease.newVersion=${{ inputs.snapshot_version }} -Prelease.failOnCommitNeeded=false
